### ISSUE TITLE
Missing tf_conversions dependencies

### ISSUE THREAD

**Issue by joekeo** [iris-ua/iris_lama#10]
Hello,m while building lapa from a clean install I got this error:
Errors     << iris_lama_ros:cmake /home/ros_ws/logs/iris_lama_ros/build.cmake.000.log                 
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "tf_conversions"
  with any of the following names:

    tf_conversionsConfig.cmake
    tf_conversions-config.cmake

I think it is solved by addind tf_conversions to the build depends, if this is correct, I can PR the mod

**Comment by joekeo** [comment]
found that the depend ois in the iris_lama_ros, sorry my bad

**Comment by eupedrosa** [comment]
I am glad I could help :wink:
Everything ROS ralated is on https://github.com/iris-ua/iris_lama_ros (as you found out).
