### ISSUE TITLE
Shared library

### ISSUE THREAD

**Issue by reinzor** [iris-ua/iris_lama#13]
Any reason why `iris-lama` is a static library (https://github.com/iris-ua/iris_lama/blob/master/src/CMakeLists.txt#L54) and no shared library?

AFAIK, `catkin_package` `depend` is not possible with this library. Why is it different then for example [octomap](https://github.com/OctoMap/octomap/tree/devel/octomap)?

**Comment by facontidavide** [comment]
I have a little trick that I use sometime to create a CMakeLists.txt file that work both with catkin or without it. In this way it would be easier to "catkinize" for ROS users and still be ROS independent.

@eupedrosa do you want to have a look to a potential PR?

**Comment by eupedrosa** [comment]
Hi @reinzor ,
There is no reason for `iris-lama`to be a static library. It is some sort of legacy decision that I already forgot. I have no problems in switching to a shared library. 

@facontidavide, your PR breaks https://github.com/iris-ua/iris_lama_ros, but that is OK. I will accept the commit and provide the necessary to the ros package.

**Comment by reinzor** [comment]
That was quick, thanks @eupedrosa and @facontidavide !
