### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by reinzor** [iris-ua/iris_lama#17]
Hi, are there any plans to release `iris_lama` and `iris_lama_ros` for ROS Kinetic, Melodic, Noetic?

**Comment by facontidavide** [comment]
![image](https://user-images.githubusercontent.com/2822888/79327056-1c5aaf00-7f14-11ea-96d9-c7544c8ddd5e.png)

**Comment by eupedrosa** [comment]
Hi. 
Yes, there are plans to release `iris_lama` and `iris_lama_ros`.  I am a *noob* to releases, so I do not know when it will be done. 

I have some doubts about `iris_lama_ros` as a package name. I do not know if it is acceptable. So I have to figure this out.

That said, any help to accelerate the process is welcomed.

PS: We started a ROS2 port. We may release for ROS2 in the future.

**Comment by facontidavide** [comment]
I would say that I can help you, but really, you just need to follow this step by step ;) 

http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

**Comment by eupedrosa** [comment]
> I would say that I can help you, but really, you just need to follow this step by step ;)
>
>http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

I recall that you already told me how to do it, @facontidavide.
I am gonna leave this issue open until I do a proper release.

**Comment by eupedrosa** [comment]
Hi @facontidavide and @reinzor.
I did the release for `iris_lama` and `iris_lama_ros` will follow (maybe tomorrow). For now, I've only did a melodic release. Do you also use `iris_lama` in `kinect`?

**Comment by facontidavide** [comment]
We used to, but we are migrating to melodic. Still, it is not much work to release it for kinetic too 😉

**Comment by eupedrosa** [comment]
I've release both package. Unfortunatly, I believe that `iris_lama_ros` will not be on the next release of melodic. Before `iris_lama` was merged, `bloom` issued a warning for `iris_lama_ros` that `iris_lama` was not found (it is a dependency).

Now, it is just a matter of time until both packages are available through `apt-get`.

I do not have plans to support Kinect. I want to maintain Melodic and the next ROS release Noetic. There is also the possibility to support ROS2. It is already running in Dashing and Eloquent :smile:

**Comment by facontidavide** [comment]
do not worry about the apparent "missingdependency". When they are released together, the CI of ROS will not complain anymore

**Comment by eupedrosa** [comment]
You are right, I could have ignore it and publish `iris_lama_ros` sooner. Always learning..
