### ISSUE TITLE
Run in Ubuntu 18

### ISSUE THREAD

**Issue by Zumbalamambo** [iris-ua/iris_lama#18]
How do I run it in Ubuntu and How do I configure the localization for different camera settings?

**Comment by eupedrosa** [comment]
Hi @Zumbalamambo,

You can read the [README](../blob/master/README.md) for more information.
Note that `iris_lama` is only a library. For running binaries check [iris_lama_ros](https://github.com/iris-ua/iris_lama_ros).
The localization algorithm was designed for lasers and not cameras.
