### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by reinzor** [iris-ua/iris_lama#22]
Seems to build nicely under `Ubuntu 20.04 / Noetic`, can we get a release?

**Comment by eupedrosa** [comment]
> Seems to build nicely under Ubuntu 20.04 / Noetic

That includes https://github.com/iris-ua/iris_lama_ros?

If everything is compiling and running fine, I see a possible release in a near future.

**Comment by eupedrosa** [comment]
Release created. Hopefully, it will be available in the next noetic sync.
