### ISSUE TITLE
DynamicDistanceMap

### ISSUE THREAD

**Issue by TianfaYao** [iris-ua/iris_lama#23]
The code is very clear and worship, but I simulate Dynamic_distance_map separately and found that when removeObstacle, there is a minor problem, the related removal cell sqdist is not cleared, maybe this should be the case here;

`void lama::DynamicDistanceMap::raise(const Vector3ui& location, distance_t& current)
{
    Vector3ui newloc;
    const int numOfNeighbor = is_3d ? 26 : 8;
    for (int i = 0; i < numOfNeighbor; ++i){

        Vector3l d(deltas_[i][0], deltas_[i][1], deltas_[i][2]);

        newloc = (location.cast<int64_t>() + d).cast<uint32_t>();
        distance_t* neighbor = (distance_t*) get(newloc);
        if (neighbor == 0 or neighbor->is_queued)
            continue;

        if (not neighbor->valid_obstacle)
            continue;

        const distance_t* obstacle = (distance_t*) get(neighbor->obstacle);
        if (obstacle == 0)
            continue;

        // verify if the closest point is no longer an obstacle.
        if (not obstacle->sqdist == 0){
            raise_.push({neighbor->sqdist, newloc});

            neighbor->obstacle       = current.obstacle;
            neighbor->valid_obstacle = false;
            neighbor->is_queued      = true;
        }else if(not neighbor->is_queued){
            lower_.push({neighbor->sqdist, newloc});

            neighbor->is_queued = true;
        }

    }// end for

    current.is_queued = false;
}`
`
        // verify if the closest point is no longer an obstacle.
        if (not obstacle->sqdist == 0){
            raise_.push({neighbor->sqdist, newloc});
            neighbor->sqdist         = max_sqdist_;
            neighbor->obstacle       = current.obstacle;
            neighbor->valid_obstacle = false;
            neighbor->is_queued      = true;
        }else if(not neighbor->is_queued){
            lower_.push({neighbor->sqdist, newloc});

            neighbor->is_queued = true;
        }
`

**Comment by TianfaYao** [comment]
The code is very clear and worship, but I simulate Dynamic_distance_map separately and found that when removeObstacle, there is a minor problem, the related removal cell sqdist is not cleared, maybe this should be the case here;
**dynamic_distance_map**
`void lama::DynamicDistanceMap::raise(const Vector3ui& location, distance_t& current)
{
---
if (not obstacle->sqdist == 0){
            raise_.push({neighbor->sqdist, newloc});

            neighbor->obstacle       = current.obstacle;
            neighbor->valid_obstacle = false;
            neighbor->is_queued      = true;
        }
---
change to
---
if (not obstacle->sqdist == 0){
raise_.push({neighbor->sqdist, newloc});
neighbor->sqdist = max_sqdist_;
neighbor->obstacle = current.obstacle;
neighbor->valid_obstacle = false;
neighbor->is_queued = true;
}
---
}`

**Comment by eupedrosa** [comment]
Hi @TianfaYao.

Clearing the `sqdist` of a raised value is not necessary. There are two reason why:
1. If the cell has a new close obstacle, it will be changed by the `lower()` operation.
2. If the cell is no longer touched (due to the max propagation wave size), it will have `valid_obstacle = false`. The `distance()` function will return the maximum distance if `valid_obstacle = false` ignoring the value in `sqdist`.

Howerver, there may be of some value to apply `neighbor->sqdist = max_sqdist_;`. The online data compression benefits from repetitive patterns.
