### ISSUE TITLE
Local minimum

### ISSUE THREAD

**Issue by TianfaYao** [iris-ua/iris_lama#24]
Hi @eupedrosa   
      the distance map use  squaredNorm even use the robust kernel is easy to local minimum ,why not use norm , I  think  some times that will improve the robust,you can try it.

**Comment by eupedrosa** [comment]
The use of the *squaredNorm* in the distance map is just to prevent the calculation of square roots during the update of the map.
The actual distance that is used is in fact the *norm*.
