### ISSUE TITLE
cmake Install support

### ISSUE THREAD

**Issue by guylevy84** [iris-ua/iris_lama#32]
Hi,

Can you please add CMake support for installation?

so it will be possible to do:

    $ git clone https://github.com/iris-ua/iris_lama
    $ cd iris_lama
    $ mkdir build
    $ cd build
    $ cmake ..
    $ make
    $ sudo make install

Thanks!

**Comment by eupedrosa** [comment]
Hi @guylevy84. I added suport for cmake install. Can you verify it works for you?

**Comment by guylevy84** [comment]
yes. works as expected.
Thank you very much @eupedrosa
