### ISSUE TITLE
catkin build error  Object library target "minisam" may not link to anything.

### ISSUE THREAD

**Issue by ZOUJIASHUAI** [iris-ua/iris_lama#33]
Errors     << iris_lama:cmake /home/jason/agv_ws/logs/iris_lama/build.cmake.000.log
CMake Error at /home/***/***/src/iris_lama-master/vendor/minisam/CMakeLists.txt:28 (target_link_libraries):
  Object library target "minisam" may not link to anything.

**Comment by eupedrosa** [comment]
You may need to clean your build directory.

**Comment by ZOUJIASHUAI** [comment]
> 

I do have clean the build dir ,I even creat a new woekspace,but still got this error

**Comment by ZOUJIASHUAI** [comment]
@eupedrosa

**Comment by eupedrosa** [comment]
That is strange, did you update both `iris_lama` and `iris_lama_ros`? What build system are you using? How can I replicate the error?

**Comment by ZOUJIASHUAI** [comment]
> 
hello
@eupedrosa  my system is ubuntu18,I followed the instructions from iris_lama_ros,I think you may can replicate the error on a new fresh ubuntu18?maybe you have already installed something else?

below is the installation instructions I followed 
cd catkin_ws
mkdir src
cd src
git clone https://github.com/iris-ua/iris_lama
git clone https://github.com/iris-ua/iris_lama_ros
cd ..
catkin config --extend /opt/ros/melodic
catkin build

**Comment by eupedrosa** [comment]
Hi @ZOUJIASHUAI, I hope it is now fixed. I test it on a fresh melodic install

**Comment by ZOUJIASHUAI** [comment]
hello @eupedrosa ,it is fixed now,Thanks a million. I really appreciate you code.
