### ISSUE TITLE
Use LZ4 library from ROS when available

### ISSUE THREAD

**Issue by facontidavide** [iris-ua/iris_lama#7]
This is related to the problem reported here: https://github.com/iris-ua/iris_lama_ros/pull/2

There might be other solutions, of course

**Comment by facontidavide** [comment]
Bad news... this is not the problem. I have tried to get rid of the external dependency and use <roslz4> instead, but the problem persists...

**Comment by eupedrosa** [comment]
What version of ROS you are using @facontidavide? I've tried to reproduce the error reported at https://github.com/iris-ua/iris_lama_ros/pull/2 but it worked fine. I am using ROS Melodic.

**Comment by facontidavide** [comment]
good news for you and bad ones for me.

I have two computers with kinetic installed. On one of them the compressed rosbag works just fine and on the other it doesn't. I suggest to close this issue for the time being and reopen it if someone else experience the same problem.

**Comment by facontidavide** [comment]
REOPENED.

I am working in Kinetic and I confirm the issue, unfortunately.

**Comment by facontidavide** [comment]
[laser_lz4.bag.zip](https://github.com/iris-ua/iris_lama/files/3754639/laser_lz4.bag.zip)

Just in case, this is my rosbag

**Comment by eupedrosa** [comment]
I just tested the code in a machine with Kinetic. I have the same problem, it crashes.

**Comment by eupedrosa** [comment]
I found the problem. The culprit is zstd and not lz4, more specifically `extern/zstd/xxhash.c`. This is an easy fix. I will push the changes.

**Comment by facontidavide** [comment]
Great
